<?php 

/**
Front end code based on:
http://stackoverflow.com/questions/10939583/add-google-trust-badge-to-magento
 by @nachito - http://stackoverflow.com/users/961455/nachito

and spec is:
https://support.google.com/trustedstoresmerchant/bin/answer.py?hl=en&answer=2609894&ctx=go#Section2

*/

?>

<?php

	if (!Mage::helper('googletrustedstores')->isEnabled()) {
		return;
	}

    $orderId = $this->getOrderId();
    $order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
    $email = $order->getCustomerEmail();
    $address = $order->getBillingAddress();
    $backorder = false;
    $download = false;
    $shipDate = new Zend_Date();
    $shipDate->add(Mage::helper('googletrustedstores')->getShipDays(), Zend_Date::DAY);
    
    $url = Mage::getBaseUrl();
    $urlObject = Mage::getModel('core/url')->parseUrl($url);
    $host = $urlObject->getHost();
?>


<!-- START Trusted Stores Order -->
<div id="gts-order" style="display:none;">

  	<!-- start order and merchant information -->
	<span id="gts-o-id"><?php echo $orderId; ?></span>
	<span id="gts-o-domain"><?php echo $host; ?></span>
	<span id="gts-o-email"><?php echo htmlentities($email); ?></span>
	<span id="gts-o-country"><?php echo htmlentities($address->getCountryId()); ?></span>
	<span id="gts-o-currency">USD</span> <!-- USD only at the moment -->
	<span id="gts-o-total"><?php echo $order->getGrandTotal(); ?></span>
	<span id="gts-o-discounts"><?php echo $order->getDiscountAmount(); ?></span>
	<span id="gts-o-shipping-total"><?php echo $order->getShippingAmount(); ?></span>
	<span id="gts-o-tax-total"><?php echo $order->getTaxAmount(); ?></span>
	<span id="gts-o-est-ship-date"><?php echo $shipDate->toString('yyyy-MM-dd'); ?></span>
	<span id="gts-o-has-preorder"><?php echo $backorder ? 'Y' : 'N'; ?></span>
	<span id="gts-o-has-digital"><?php echo $download ? 'Y' : 'N'; ?></span>
  

	<?php foreach ($order->getAllItems() as $item): ?>

		<?php  if($item->getParentItemId()) continue; // skip child items ?>
	
		<span class="gts-item">
			<span class="gts-i-name"><?php echo htmlentities($item->getName()); ?></span>
			<span class="gts-i-price"><?php echo $item->getBasePrice(); ?></span>
			<span class="gts-i-quantity"><?php echo (int)$item->getQtyOrdered(); ?></span>
		</span>
		
	<?php endforeach; ?>

</div>
<!-- END Trusted Stores -->